name: Automated tests

on:
  push:
    branches: [master]
    paths-ignore:
      - 'images/**'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build code
      run: swift build
